apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: chat-app
type: Opaque
stringData:
  jwt-secret: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc2MjI0OTU0NywiaWF0IjoxNzYyMjQ5NTQ3fQ.SIEQF8tTjbcROHw7eJPwb-qCQN8ldeIuGJr0j30cZhE"